# Introdução ao try/except 
# try -> tentar executar o código
# except -> ocorreu algum erro ao tentar executar

numero = input('Vou dobrar o número que vc digitou: ')

numero_int = int(numero)
print(f'O dobro de {numero} é {numero_int * 2}')

#print(f'O dobro de {numero} é {numero_float * 2:.0f}')